// themes/index.js
// Theme engine. One object per company. URL slug drives everything.

export const themes = {
  _base: {
    companyName: "Base",
    primaryColor: "#00e5ff",
    bgColor: "#0a0a0a",
    surfaceColor: "#111111",
    textColor: "#f0f0f0",
    mutedColor: "#555555",
    heroTagline: "Building pipelines\nthat don't break\nat 3 AM.",
    brandPersonality: null,
  },
  nvidia: {
    companyName: "NVIDIA",
    primaryColor: "#76b900",
    bgColor: "#0a0a0a",
    surfaceColor: "#0f1a00",
    textColor: "#e8f5d0",
    mutedColor: "#3d5c00",
    heroTagline: "Parallelized thinking.\nGPU-grade data pipelines.\nBuilt to scale.",
    brandPersonality: "You're building the infrastructure layer for the next generation of AI. I build the data pipelines and MLOps systems that keep models in production — not just notebooks.",
  },
  netflix: {
    companyName: "Netflix",
    primaryColor: "#e50914",
    bgColor: "#141414",
    surfaceColor: "#1f1f1f",
    textColor: "#ffffff",
    mutedColor: "#555555",
    heroTagline: "Now streaming:\nAishwarya Vedaraman.\nData Engineer. S01E01.",
    brandPersonality: "Netflix runs on data — recommendation systems, A/B testing at scale, real-time streaming pipelines. My background in high-throughput ETL, MLOps, and anomaly detection maps directly to the infrastructure problems your data platform team is solving.",
  },
  spotify: {
    companyName: "Spotify",
    primaryColor: "#1db954",
    bgColor: "#121212",
    surfaceColor: "#181818",
    textColor: "#ffffff",
    mutedColor: "#535353",
    heroTagline: "Playing next:\nYour new favorite\nData Engineer.",
    brandPersonality: "Spotify's personalization challenges — real-time event processing, ML-driven features, streaming at scale — are exactly what I've built for.",
  },
  meta: {
    companyName: "Meta",
    primaryColor: "#0082fb",
    bgColor: "#0a0a0f",
    surfaceColor: "#0f1020",
    textColor: "#e8eaf6",
    mutedColor: "#3a3d5c",
    heroTagline: "Connecting data.\nConnecting people.\nBuilding at scale.",
    brandPersonality: "Meta operates some of the world's most complex data infrastructure. My experience across enterprise-scale pipelines and LangGraph/RAG work aligns with the cross-functional data engineering your teams are doing.",
  },
  databricks: {
    companyName: "Databricks",
    primaryColor: "#ff3621",
    bgColor: "#0a0a0a",
    surfaceColor: "#1a0a08",
    textColor: "#fff5f3",
    mutedColor: "#5c2a22",
    heroTagline: "Lakehouse native.\nSpark-fluent.\nReady to ship.",
    brandPersonality: "I'm Spark-fluent, Delta Lake aware, and deeply interested in the lakehouse architecture your platform is built around. Pipeline Autopilot maps cleanly to your Mosaic AI stack.",
  },
  snowflake: {
    companyName: "Snowflake",
    primaryColor: "#29b5e8",
    bgColor: "#0a0c10",
    surfaceColor: "#0d1520",
    textColor: "#dff4fd",
    mutedColor: "#1a3a52",
    heroTagline: "Cloud-native thinking.\nZero-copy architecture.\nData that scales.",
    brandPersonality: "My background in schema validation, anomaly detection, and orchestrated pipelines is a natural fit for the performance and data quality problems your engineering teams face.",
  },
  "capital-one": {
    companyName: "Capital One",
    primaryColor: "#d03027",
    bgColor: "#0a0a0a",
    surfaceColor: "#1a0808",
    textColor: "#f5e8e8",
    mutedColor: "#5c2020",
    heroTagline: "Data-driven decisions.\nEnterprise-grade pipelines.\nFintech ready.",
    brandPersonality: "Capital One is a tech company that happens to do banking. Real-time fraud detection, risk modeling pipelines, compliant data infrastructure — that's the kind of high-stakes, high-throughput work I've built for.",
  },
  google: {
    companyName: "Google",
    primaryColor: "#4285f4",
    bgColor: "#0a0a0a",
    surfaceColor: "#0f1420",
    textColor: "#e8f0fe",
    mutedColor: "#3a4a7c",
    heroTagline: "Indexing experience.\nSearching for impact.\nReady to scale.",
    brandPersonality: "Google runs on data at a scale most engineers never touch. My experience with distributed pipelines, data quality systems, and ML infrastructure aligns with the engineering challenges your teams face daily.",
  },
  amazon: {
    companyName: "Amazon",
    primaryColor: "#ff9900",
    bgColor: "#0a0a0a",
    surfaceColor: "#1a1100",
    textColor: "#fff8e8",
    mutedColor: "#5c3a00",
    heroTagline: "Day 1 thinking.\nPipelines that deliver.\nCustomer-obsessed data.",
    brandPersonality: "Amazon's data engineering challenges span e-commerce, cloud, logistics, and AI. I think in systems, bias toward action, and build pipelines designed for the scale AWS operates at.",
  },
  apple: {
    companyName: "Apple",
    primaryColor: "#f5f5f7",
    bgColor: "#000000",
    surfaceColor: "#1c1c1e",
    textColor: "#f5f5f7",
    mutedColor: "#636366",
    heroTagline: "Precision engineering.\nPrivacy-first pipelines.\nDesigned to just work.",
    brandPersonality: "Apple's data infrastructure is built around privacy, performance, and quality at every layer. I bring the same obsessive attention to data quality, schema design, and pipeline reliability.",
  },
  microsoft: {
    companyName: "Microsoft",
    primaryColor: "#00a4ef",
    bgColor: "#0a0a10",
    surfaceColor: "#0d1520",
    textColor: "#ddeeff",
    mutedColor: "#1a3a5c",
    heroTagline: "Cloud-first mindset.\nAzure-native pipelines.\nEnterprise at heart.",
    brandPersonality: "My Mphasis background is Azure-native — Synapse, Data Factory, Databricks on Azure. I already speak your stack.",
  },
  stripe: {
    companyName: "Stripe",
    primaryColor: "#635bff",
    bgColor: "#0a0a0f",
    surfaceColor: "#0f0f1a",
    textColor: "#e8e8ff",
    mutedColor: "#3a3a7c",
    heroTagline: "Payments at scale.\nData that never drops.\nInfrastructure that earns trust.",
    brandPersonality: "Stripe's reliability bar is one of the highest in the industry. I build pipelines with the same obsession — schema validation, anomaly detection, zero silent failures.",
  },
  airbnb: {
    companyName: "Airbnb",
    primaryColor: "#ff5a5f",
    bgColor: "#0a0a0a",
    surfaceColor: "#1a0a0b",
    textColor: "#ffe8e8",
    mutedColor: "#5c2022",
    heroTagline: "Data that belongs\neverywhere.\nPipelines that feel like home.",
    brandPersonality: "Airbnb pioneered the modern data stack — Minerva, Airflow, Superset. I'm fluent in that ecosystem and deeply interested in the kind of trust-in-data engineering your platform team has built.",
  },
  uber: {
    companyName: "Uber",
    primaryColor: "#06c167",
    bgColor: "#0a0a0a",
    surfaceColor: "#0a1a12",
    textColor: "#e0f5ea",
    mutedColor: "#1a4a30",
    heroTagline: "Real-time at scale.\nZero-latency pipelines.\nMoving data forward.",
    brandPersonality: "Uber's real-time data challenges — surge pricing, ETA prediction, driver allocation — require sub-second pipeline reliability. That's the performance bar I build to.",
  },
  linkedin: {
    companyName: "LinkedIn",
    primaryColor: "#0077b5",
    bgColor: "#0a0c10",
    surfaceColor: "#0d1520",
    textColor: "#ddeeff",
    mutedColor: "#1a3a5c",
    heroTagline: "Connecting talent\nto opportunity.\nAt petabyte scale.",
    brandPersonality: "LinkedIn's data engineering team powers economic opportunity for 900M+ members. My background in graph-adjacent data systems and ML pipelines maps directly to the problems your team is solving.",
  },
  openai: {
    companyName: "OpenAI",
    primaryColor: "#10a37f",
    bgColor: "#0a0a0a",
    surfaceColor: "#0a1a15",
    textColor: "#e0f5ef",
    mutedColor: "#1a4a38",
    heroTagline: "Training data pipelines.\nMLOps at the frontier.\nBuilding what's next.",
    brandPersonality: "OpenAI's data infrastructure underpins the most impactful AI systems ever built. My MLOps and pipeline background — CI/CD failure prediction, data quality engineering, LangGraph agents — is built for exactly this kind of work.",
  },
  anthropic: {
    companyName: "Anthropic",
    primaryColor: "#cc785c",
    bgColor: "#0a0805",
    surfaceColor: "#150f0a",
    textColor: "#f5ede8",
    mutedColor: "#5c3a2a",
    heroTagline: "Responsible AI.\nTrustworthy data.\nSafety through engineering.",
    brandPersonality: "Anthropic's mission requires data systems you can trust completely — auditable, reliable, bias-aware. That's how I build: quality gates, schema validation, anomaly detection baked in from day one.",
  },
  palantir: {
    companyName: "Palantir",
    primaryColor: "#aaaaaa",
    bgColor: "#050505",
    surfaceColor: "#0d0d0d",
    textColor: "#cccccc",
    mutedColor: "#444444",
    heroTagline: "Data as infrastructure.\nDecisions at machine speed.\nBuilt for the hard problems.",
    brandPersonality: "Palantir works on the hardest data integration problems in the world. I build systems designed for messy, high-stakes, schema-inconsistent real-world data — exactly the environment Foundry was built for.",
  },
  coinbase: {
    companyName: "Coinbase",
    primaryColor: "#0052ff",
    bgColor: "#0a0a10",
    surfaceColor: "#0d1020",
    textColor: "#e0e8ff",
    mutedColor: "#1a2a5c",
    heroTagline: "On-chain data.\nFinancial-grade pipelines.\nBuilding open finance.",
    brandPersonality: "Coinbase's data infrastructure powers financial decisions for millions of users. I build with the auditability, reliability, and compliance mindset that financial data demands.",
  },
  figma: {
    companyName: "Figma",
    primaryColor: "#a259ff",
    bgColor: "#0a0a0f",
    surfaceColor: "#0f0a1a",
    textColor: "#ede8ff",
    mutedColor: "#3a2a5c",
    heroTagline: "Design systems.\nData systems.\nBoth need good architecture.",
    brandPersonality: "Figma's data engineering challenges are about making creative workflows measurable. I bring both the technical rigor and systems-thinking to instrument and analyze product data at scale.",
  },
  salesforce: {
    companyName: "Salesforce",
    primaryColor: "#00a1e0",
    bgColor: "#0a0c10",
    surfaceColor: "#0d1520",
    textColor: "#ddeeff",
    mutedColor: "#1a3a5c",
    heroTagline: "CRM meets data engineering.\nTrusted pipelines.\nCustomer 360.",
    brandPersonality: "Salesforce's data platform challenges — multi-tenant architecture, real-time CRM data, Einstein AI — require engineers who understand both scale and enterprise constraints.",
  },
  twilio: {
    companyName: "Twilio",
    primaryColor: "#f22f46",
    bgColor: "#0a0a0a",
    surfaceColor: "#1a0508",
    textColor: "#ffe8ea",
    mutedColor: "#5c1018",
    heroTagline: "Communications data.\nReal-time pipelines.\nEvery message counts.",
    brandPersonality: "Twilio's event-driven architecture requires pipelines that handle high-volume, real-time messaging data reliably. That's my comfort zone.",
  },
};

// ── Company list for the switcher UI ──────────────────
export const COMPANY_LIST = [
  { slug: "_base",       name: "Default",     color: "#00e5ff" },
  { slug: "nvidia",      name: "NVIDIA",      color: "#76b900" },
  { slug: "netflix",     name: "Netflix",     color: "#e50914" },
  { slug: "spotify",     name: "Spotify",     color: "#1db954" },
  { slug: "meta",        name: "Meta",        color: "#0082fb" },
  { slug: "google",      name: "Google",      color: "#4285f4" },
  { slug: "amazon",      name: "Amazon",      color: "#ff9900" },
  { slug: "apple",       name: "Apple",       color: "#f5f5f7" },
  { slug: "microsoft",   name: "Microsoft",   color: "#00a4ef" },
  { slug: "openai",      name: "OpenAI",      color: "#10a37f" },
  { slug: "anthropic",   name: "Anthropic",   color: "#cc785c" },
  { slug: "databricks",  name: "Databricks",  color: "#ff3621" },
  { slug: "snowflake",   name: "Snowflake",   color: "#29b5e8" },
  { slug: "capital-one", name: "Capital One", color: "#d03027" },
  { slug: "stripe",      name: "Stripe",      color: "#635bff" },
  { slug: "palantir",    name: "Palantir",    color: "#aaaaaa" },
  { slug: "airbnb",      name: "Airbnb",      color: "#ff5a5f" },
  { slug: "uber",        name: "Uber",        color: "#06c167" },
  { slug: "linkedin",    name: "LinkedIn",    color: "#0077b5" },
  { slug: "coinbase",    name: "Coinbase",    color: "#0052ff" },
  { slug: "salesforce",  name: "Salesforce",  color: "#00a1e0" },
  { slug: "twilio",      name: "Twilio",      color: "#f22f46" },
  { slug: "figma",       name: "Figma",       color: "#a259ff" },
];

export function getThemeFromSlug(slug) {
  return themes[slug?.toLowerCase()] || themes["_base"];
}
